### ISSUE TITLE
Collecting page data .ReferenceError: self is not defined on build - NextJS

### ISSUE THREAD

**Issue by nsikanikpoh** [andrewraygilbert/quill-to-word#7]
**I get the following error when running** `yarn build` 
I am using `quill-to-word` on NextJS with **dynamic import**. It works fine locally, unfortunately, the build isn't successful.

```const initQuillWord = async () => {
      const quillWLib = (await import('quill-to-word'));
      setQuillToWord(quillWLib)
    }

  initQuillWord()
```
>info  - Creating an optimized production build  
info  - Compiled successfully
info  - Collecting page data .ReferenceError: self is not defined
    at Object.<anonymous> (D:\............................................\node_modules\quill-to-pdf\dist\main.js:2:202)
    at Module._compile (node:internal/modules/cjs/loader:1254:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1308:10)
    at Module.load (node:internal/modules/cjs/loader:1117:32)
    at Module._load (node:internal/modules/cjs/loader:958:12)
    at Module.require (node:internal/modules/cjs/loader:1141:19)
    at require (node:internal/modules/cjs/helpers:110:18)
    at 1901 (D:\........................\.next\server\pages\doc\[id].js:1356:18)
    at __webpack_require__ (D:\........................................................\.next\server\webpack-runtime.js:25:42)
    at D:\............................\.next\server\pages\doc\[id].js:356:71
 Build error occurred
Error: Failed to collect page data for /doc/[id]
    at D:\...........................................................\node_modules\next\dist\build\utils.js:959:15 {
  type: 'Error'
}
>

**Comment by nsikanikpoh** [comment]
**Here's how I worked around it.**
I created a **Singleton** to **return** it from another file:

```
//quillToWord.tsx
import * as quillToWord from 'quill-to-word';

let PluginSingleton: any = (function () {

  return {
    generateWord: async function (delta: any, quillToWordConfig: any) {
      return await quillToWord.generateWord(delta, quillToWordConfig);
    }
  };
})();

const SingletonPlugin = PluginSingleton;

export default SingletonPlugin;
```

And the caller function:

```
const processWord = async () =>{
  if(quillRef.current){
    const delta = quillRef.current.getEditor().getContents();
    const quillToWordConfig: any = {
        exportAs: 'blob'
    };

    const quillToWord = (await import('./quillToWord')).default; 
    const docAsBlob = await quillToWord.generateWord(delta, quillToWordConfig);
    saveAs(docAsBlob, `word-import.docx`);
  }
}
```

**Calling it like** `const quillToWord = (await import('./quillToWord')).default; ` works.
I hope someone finds it useful.
